### ISSUE TITLE
Automatic pane closing

### ISSUE THREAD

**Issue by tamielbr** [Jumagreens/AfyaMap#7]
Hi! I'm using your code on https://github.com/tamielbr/datatables-map, and I can't seem to find what trigger the automatic closing of the pane the first time a pin is clicked. It seems like when you click it first, the window/div closes after 1 second. After that, if you click again, it stays. Do you know where this setting is? Thanks!

**Comment by tamielbr** [comment]
Found it, just removed:
`setTimeout(function () { 
sidebar.hide();
 }, 5000);`

**Comment by gr2m** [comment]
:+1:
